# Generated by Django 2.1.1 on 2018-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuseumObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان شیء')),
                ('description', models.TextField(verbose_name='توضیحات مربوط به شیء')),
                ('image', models.ImageField(upload_to='media/object-image', verbose_name='تصویر شیء')),
            ],
        ),
    ]
