# Generated by Django 2.1.1 on 2018-09-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_museumobject_ded_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='museumobject',
            name='ded_id',
            field=models.IntegerField(verbose_name='شناسه شیء'),
        ),
    ]
